env: 'habitat'
calibrate_only: true

calibration:
  num_temp: 5
  grid_points: 100
  grid_points_simpleset: 5
  calibration_set_size: 400
  test_set_size: 400
  batch_size: 1
  num_cov_simpleset: 3
  draw_heatmap: False
  minimum_temp: 0.1
  max_miscoverage: 0.5
  equal_action_mask_dist: 1
  initial_temp: -0.2

prediction:
  data_path: /home/jlidard/risk_calibrated_interactive_planning/datasets/habitat/rollouts
  trained_model_path: /home/jlidard/rcip/trained_models/trained_models/habitatepoch300.pth
  traj_input_dim: 350
  min_traj_len: 100
  traj_len: 600
  max_pred_len: 100
